models/Conference.js

models/Conference작성 완료했습니다! 그런데 allowNull true해야할것들이 몇개 보이는데 db에는 그게 안되어있어서 일단 db에 있는대로만 작성했는데 보고 수정사항 말씀해주세용

feat: models/Conference 작성

---

app.js
controller/mainController.js
controller/userController.js
models/ConferenceReview.js
routes/main.js

main index 페이지 작동할 수 있게 했습니다.
review 모델도 작성.

feat: main 컨트롤러 추가, 리뷰 model 작성

---

app.js
routes/conference.js

conference와 관련된 라우트들을 간략하게 적어보았습니다... 추가적으로 필요한 라우트들 있으면 꼭꼭 알려주세요!! 추가해서 작성해서 git add하겠습니다!!!

feat: routes/conference 일부 작성

---

app.js

feat: app.js singleQuote

---

public/css/common.css
views/common/head.ejs

feat: axios 추가 및 common.css 추가

---

views/pages/signup.ejs

feat: 회원가입 페이지 추가

---

public/css/common.css
public/css/reset.css
views/common/header.ejs
views/pages/event/detail.ejs
views/pages/event/list.ejs
views/pages/event/write.ejs
views/pages/login.ejs
views/pages/myPage/profile.ejs
views/pages/review/detail.ejs
views/pages/review/list.ejs
views/pages/review/write.ejs

feat: 페이지 기본 구조 세팅

---

views/pages/signup.ejs

- head, header, footer 를 include로 처리
- data에 맞게 form 형식 수정. 추후 더 보완 예정(특히 주소)

feat: signup form 형식 수정

---

public/css/common/common.css
public/css/common/reset.css
public/css/pages/main.css
views/pages/index.ejs

feat: 메인페이지 & CSS 작업

---

controller/coninfoController.js
models/Conference.js
routes/conference.js

conference routes랑 controller작성했습니다..! 근데 이게 제가 풀리퀘스트를 안올렸는지 뭔가 밀려있는데 제일 뒤에꺼만 봐주시면 될 것 같아요!

Feature/conference   conference routes랑 controller작성

---

routes/user.js
views/pages/login.ejs

로그인 기본 css 랑 axios 코드 넣었습니다.
추후에 아이디 오류, 비번 오류, 서버 오류 추가 예정입니다.

feat: 로그인 페이지 기본 틀 작업

---

public/css/pages/review/editorStyle.css
public/css/pages/review/write.css
public/js/editor.js
views/pages/review/write.ejs

feat: 리뷰 페이지 수정 및 에디터 기능 추가

---

public/css/common/common.css
views/common/footer.ejs
views/pages/event/write.ejs
views/pages/signup.ejs

1. 온라인/오프라인이 불리안으로 잘 넘어가는지 확인 필요.
2. 행사 가격 conPrice DB로 넘어가기 전 숫자로 변환 필요.
3. jQuery는 미완성... 추후 보완 하겠슴다

feat: 행사 등록 페이지 기본 form

---

views/pages/event/write.ejs

행사 작성페이지 axios post요청 완료했습니다~!! 폼부분에서 약간 오류가 있어서 수정하면 될 것 같아요!

feat: event/write axios post

---

views/pages/event/write.ejs

feat: event-write 오류 수정, jQuery 기능 구현, fileupload 추가

---

app.js
routes/conference.js
views/pages/event/write.ejs

app.js routes/conference수정했습니다

feat: app.js ,routes/conference수정

---

models/Conference.js
views/pages/event/write.ejs

feat: conference db수정(con_detail, con_image 컬럼 추가

---

controller/coninfoController.js
views/pages/event/list.ejs
views/pages/event/write.ejs

feat:event-list 기본 틀, 필터, 달력, 카드리스트 구현

---

controller/coninfoController.js
models/Conference.js
views/pages/event/detail.ejs

Feature/conference7 행사 상세페이지 조회수 증가

---

controller/coninfoController.js
routes/conference.js
views/pages/event/list.ejs

feat: 행사 목록 페이지 데이터 전송 라우터 추가, 기존 라우터에서 데이터 보내는 것 삭제

---

public/css/pages/review/list.css
views/pages/review/list.ejs

feat: review-list css

---

controller/coninfoController.js
routes/conference.js
views/pages/event/list.ejs
views/pages/myPage/manager.ejs

feat: 관리자 페이지에 승인안된 행사들 정보 전송(일단은 send로)

---

controller/coninfoController.js
public/js/eventList.js
routes/conference.js
views/pages/event/list.ejs

- 행사 필터 기능 추가 ( is_onoff = 0이 온라인 1이 오프라인으로 구성 )

feat: 행사 필터 기능 추가

---

controller/coninfoController.js
public/js/eventList.js
views/common/components/conLocationSelect.ejs
views/pages/event/list.ejs
views/pages/event/write.ejs

- 달력 필터링 구현
- 지역 select 컴포넌트화
- 행사 분야 여러개 선택되도록 기능 구현

feat: 달력 기능 구현

---

public/css/pages/signup.css
views/pages/signup.ejs

feat: 회원가입 css 하는 중

---

controller/userController.js
routes/user.js
views/pages/signup.ejs

제곧내
근데 중복체크할때도 유효성검사 넣었어요.. 
실컷 중복체크까지 했는데 회원가입등록버튼 눌렀더니 아이디 다시 입력하라 그러면 빡칠것 같아서..

feat: 회원가입 유효성검사

---

public/css/pages/signup.css
views/pages/signup.ejs

사라진... 회원 가입 css 파일 다시 찾아서 올립니다.
이번에는 되길

feat: 회원가입 css

---

controller/coninfoController.js
models/index.js
routes/conference.js
views/pages/event/detail.ejs

feat: 행사 찜 구현

---

views/pages/myPage/myFavoriteCon.ejs
views/pages/myPage/myReviewList.ejs
views/pages/myPage/profileAside.ejs
views/pages/myPage/profileUpdate.ejs

기본 틀 및 data 출력 확인
1. 사이드 메뉴바 연결 링크 통일하는 작업 필요.
2. myFavoriteCon에서 이미지 data 못 불러옴.
3. 내가 쓴 리뷰와 내가 찜한 행사 render 방식 수정 논의 필요.

feat: 마이페이지 기본 틀 및 data 확인

---

config/config.json

docs: Delete config/config.json

---

public/css/common/common.css
views/common/footer.ejs

나중에 프로젝트 깃허브로 링크 연결하는 것도 좋을 것 같습니다!
지금은 이렇게 하고 나중에 더 좋은 아이디어 있으면 바꿀게요.

feat: footer 디자인 변경

---

views/pages/myPage/myReviewList.ejs
views/pages/myPage/profileAside.ejs
views/pages/myPage/profileUpdate.ejs

마이페이지: 사이드 메뉴 불필요 문구 제거 
프로필 수정 페이지: select 수정
내가 쓴 리뷰 페이지:  리뷰 목록 table로 변경

feat: 프로필 select 수정, 리뷰 목록 table로 변경

---

models/Conference.js
models/ConferenceReview.js
package-lock.json
package.json

merge 후 
npm install moment --save  명령어 실행

refector: dateformat 수정을 수정을 위한 moment.js 설치, models 리팩토링

---

public/css/pages/event/detail.css
public/js/eventDetail.js
views/pages/event/detail.ejs

feat:행사 상세페이지 버튼 누르면 해당 내용으로 가도록 만드는 중

---

package-lock.json
package.json
public/js/editor.js
public/js/eventWrite.js
routes/main.js
utils/utils.js

- 모든 이미지가 1920 x 1080으로 변경 되게 수정하였습니다.
- 서버에서 이미지 경로를 수정합니다.

feat: 이미지 경로 수정 및 이미지 해상도 고정값 추가

---

controller/mainController.js

코드작성 시 생긴 이슈
const currentDate = moment();
const oneMonthAgo = currentDate.subtract(1, ‘months’); // 안됨
const currentDate = moment();
const oneMonthAgo = moment().subtract(1, ‘months’); // 됨
---- 위 와 같은 경우
const oneMonthAgo = currentDate.subtract(1, ‘months’); 에서
currentDate 객체를 (현재시간) 간섭하게 됨 (1달전으로 바뀌게됨)
그렇기 때문에 
const oneMonthAgo = moment().subtract(1, ‘months’); 
moment()로 새로운 객체에 subtract 해줘야함

feat: 메인페이지 review 정렬방법 수정

---

public/css/pages/myPage/managerAside.css
views/pages/myPage/allConference.ejs
views/pages/myPage/allUser.ejs
views/pages/myPage/conferenceHandler.ejs
views/pages/myPage/managerAside.ejs
views/pages/myPage/myFavoriteCon.ejs
views/pages/myPage/myRegisterCon.ejs
views/pages/myPage/myReviewList.ejs
views/pages/myPage/profileAside.ejs
views/pages/myPage/profileUpdate.ejs

제가 branch 가 헷갈려서 한 번 머지하고 작업 이어나가겠습니다..

feat: 마이페이지 반응형 사이드바 작업 중

---

views/pages/signup.ejs

feat:회원가입 이름 2글자부터 5글자까지(한글로)유효성검사

---

public/css/pages/main.css
views/pages/index.ejs
views/pages/myPage/myRegisterCon.ejs
views/pages/myPage/profileUpdate.ejs

1. 내가 등록한 행사 버그 수정 후 css 재배치
2. 메인 페이지 알고리즘 관련 문구 추가 후 css 수정
3. 프로필 수정 페이지 문구 추가

feat: 등록행사 버그 수정 후 css, 메인페이지&프로필 수정 문구 추가

---

public/css/pages/main.css
views/pages/index.ejs

커서랑 CRUD에 색상를 넣으려고 했는데 
줄바꿈 된 상태로,,, 이상해져서 뺐습니다.

feat: 메인페이지 typing responsive

---

views/pages/index.ejs

한국인의 속도에 맞게 좀 더 빠르게 바꾸고, 화면이 지저분해지는 것 같아서 지우는 효과도 넣었습니다.

feat:typing 속도 조절

---

public/css/pages/myPage/managerAside.css
public/css/pages/myPage/myRevList.css
views/pages/myPage/myRegisterCon.ejs
views/pages/myPage/myReviewList.ejs
views/pages/myPage/profileUpdate.ejs

찜 기능 구현되면 내가 찜한 행사 페이지도 반응형 완성하겠습니다.

feat: 마이페이지 반응형 찜행사 제외

---

public/css/pages/myPage/managerAside.css
views/pages/myPage/allConference.ejs
views/pages/myPage/allUser.ejs
views/pages/myPage/conferenceHandler.ejs
views/pages/myPage/myFavoriteCon.ejs
views/pages/myPage/myReviewList.ejs

관리자 페이지 중 행사 관리 페이지도 반응형 작업해서 다른 branch 로 올리겠습니다

feat: 관리자 페이지 중 유저&행사 조회 반응형 구현 완료

---

public/css/common/root.css
public/css/pages/myPage/conHandler.css
public/css/pages/myPage/managerAside.css
views/pages/index.ejs
views/pages/login.ejs
views/pages/myPage/allConference.ejs
views/pages/myPage/allUser.ejs
views/pages/myPage/conferenceHandler.ejs
views/pages/myPage/myFavoriteCon.ejs
views/pages/myPage/myReviewList.ejs
views/pages/signup.ejs

1. 메인페이지 타이핑 지우기 효과 제거(reason: 화면이 흔들림)
2. 마이페이지&관리자페이지에서 사이드바 다른 색상 사용한 것 통일
3. 마이페이지&관리자페이지에서 reload 추가

feat: 마이페이지 & 관리자페이지 반응형 완성, 주석 제거

---

public/css/common/common.css
public/css/pages/myPage/conHandler.css
views/pages/myPage/allConference.ejs
views/pages/myPage/conferenceHandler.ejs
views/pages/myPage/myFavoriteCon.ejs
views/pages/myPage/myRegisterCon.ejs
views/pages/myPage/myReviewList.ejs

마이 페이지 & 관리자 페이지
- 데이터 출력 오류 수정: 승인 대기 행사도 거절로 떴었음
- 버튼 변경
- td vertical align : middle
메인 페이지
- CRUD font weight 변화

feat: 데이터 출력, 버튼 변경, 정렬
